
<nav>
  <ul>
    <li><a href="/index.html"><i class="fa fa-home fa-lg" aria-hidden="true"></i>&nbsp;Home</a></li>
    <li><a href="/resources.html"><i class="fa fa-cubes fa-lg" aria-hidden="true"></i>&nbsp;Resources</a></li>
    <li><a href="/projects.html"><i class="fa fa-tasks fa-lg" aria-hidden="true"></i>&nbsp;Projects</a></li>
    <li><a href="/about.html"><i class="fa fa-bullhorn fa-lg" aria-hidden="true"></i>&nbsp;About</a></li>
  </ul>
</nav>
